# Generated by Django 4.2.11 on 2024-06-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
